services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=quizdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'



  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: edougajean@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'

